AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  ninjaduds-lambda

  Sample SAM Template for ninjaduds-lambda

#create a s3 bucket
#aws s3 mb s3://bucket-name

#NOTES:
# Changing Lambda function resource name or mapping to new handler name does NOT change API Endpoint domain
# Changing Lamdba API endpoint path does not change Endpoint Url domain

#PARAMETERS DO NOT WORK (YET!)
# Parameters: 
#   EnvTypeParam: 
#     Type: String
#     Default: Local
#     AllowedValues: [Local, Dev, Stage, Prod]
#     Description: Enter Local, Dev, Stage, Prod. Default is Local.

# Conditions: 
#   CreateLocalResources: !Equals [ !Ref EnvTypeParam, Local ]
#   CreateStageResources: !Equals [ !Ref EnvTypeParam, Stage ]
#   CreateProdResources: !Equals [ !Ref EnvTypeParam, Prod ]
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
    Environment:
      Variables:
        LocalIp: 192.168.1.22
        LocalDynamoDbPort: 8000
        TableName: NinjaDudsMainTablexxLocalxx
        EnvType: xxLocalxx
        Bucket: ninjaduds-prod-alan-purugganan

Resources:
  DBUpdatexxLocalxx:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: api/
      Handler: app.dbUpdate
      Runtime: nodejs12.x
      Role: arn:aws:iam::518635498583:role/NinjaDudsRole
      Events:
        NinjaDuds:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /db-update
            Method: post

  DBPutxxLocalxx:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: api/
      Handler: app.dbPut
      Runtime: nodejs12.x
      Role: arn:aws:iam::518635498583:role/NinjaDudsRole
      Events:
        NinjaDuds:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /db-put
            Method: post
  

  DBGetxxLocalxx:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: api/
      Handler: app.dbGet
      Runtime: nodejs12.x
      Role: arn:aws:iam::518635498583:role/NinjaDudsRole
      Events:
        NinjaDuds:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /db-get
            Method: post
      
  S3DownloadxxLocalxx:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: api/
      Handler: app.s3Download
      Runtime: nodejs12.x
      Role: arn:aws:iam::518635498583:role/NinjaDudsRole
      Events:
        NinjaDuds:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /s3-download
            Method: post

  S3UploadxxLocalxx:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: api/
      Handler: app.s3Upload
      Runtime: nodejs12.x
      Role: arn:aws:iam::518635498583:role/NinjaDudsRole
      Events:
        NinjaDuds:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /s3-upload
            Method: post

  ReadExamplesxxLocalxx:
      Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
      Properties:
        CodeUri: api/
        Handler: app.readExamples
        Runtime: nodejs12.x
        Role: arn:aws:iam::518635498583:role/NinjaDudsRole
        Events:
          NinjaDuds:
            Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
            Properties:
              Path: /read-examples
              Method: get

  WriteExamplesxxLocalxx:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: api/
      Handler: app.writeExamples
      Runtime: nodejs12.x
      Role: arn:aws:iam::518635498583:role/NinjaDudsRole
      Events:
        NinjaDuds:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /write-examples
            Method: post

#Outputs:
# ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
# Find out more about other implicit resources you can reference within SAM
# https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
# HelloWorldApi:
#   Description: "API Gateway endpoint URL for Prod stage for Hello World function"
#   Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
# HelloWorldFunction:
#   Description: "Hello World Lambda Function ARN"
#   Value: !GetAtt HelloWorldFunction.Arn
# HelloWorldFunctionIamRole:
#   Description: "Implicit IAM Role created for Hello World function"
#   Value: !GetAtt HelloWorldFunctionRole.Arn
